# Generated by Django 2.0.3 on 2019-07-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20190702_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppings',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
