# Generated by Django 2.0.3 on 2019-08-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_toppings_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='content',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
